### ISSUE TITLE
brew install fails on macOS Sierra

### ISSUE THREAD

**Issue by ns408** [jmespath/jp#10]
https://github.com/jmespath/jp#installing fails with the following on macOS Sierra (Version 10.12) with the following:

```
$ brew install jp --debug
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/jmespath/homebrew-jmespath/Formula/jp.rb
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing jp from jmespath/jmespath
/usr/local/Library/Homebrew/brew.rb (Formulary::FormulaLoader): loading /usr/local/Library/Taps/homebrew/homebrew-core/Formula/go.rb
go: This formula either does not compile or function as expected on OS X
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
/usr/local/Library/Homebrew/formula_installer.rb:325:in `check_requirements'
/usr/local/Library/Homebrew/formula_installer.rb:291:in `compute_dependencies'
/usr/local/Library/Homebrew/formula_installer.rb:131:in `verify_deps_exist'
/usr/local/Library/Homebrew/formula_installer.rb:124:in `prelude'
/usr/local/Library/Homebrew/cmd/install.rb:271:in `install_formula'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `block in install'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `each'
/usr/local/Library/Homebrew/cmd/install.rb:150:in `install'
/usr/local/Library/Homebrew/brew.rb:87:in `<main>'
VIC011967M:~ nitin.sharma 01:11 PM
$ brew install -v jp
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakages.
Please create pull-requests instead of filing issues.
==> Installing jp from jmespath/jmespath
go: This formula either does not compile or function as expected on OS X
versions newer than El Capitan due to an upstream incompatibility.
Error: An unsatisfied requirement failed this build.
```

For now, I decided to download `jp-darwin-amd64` from https://github.com/jmespath/jp/releases/tag/0.1.2 and placed it as `/usr/local/bin/jp` also chmod'ing it to `+x`.

**Comment by jamesls** [comment]
This should be working now.  I've updated the homebrew script to install directly from the prebuilt binaries on the github release page.  That way you don't need to have go installed nor compile it from source.

Let me know if `brew upgrade && brew install jp` still isn't working and I'll take another look.
